export VCS_HOME /usr/local/packages/synopsys_2018/vcs-mx/O-2018.09-SP1
#export VCS_HOME /usr/local/packages/synopsys_2015/vcs-mx/amd64/

all: compile run


#16x16 composed from 8x8
size?=16

ifeq ($(size),16)
	FILES=../design_composed/16x16_from_8x8.no_ram.gen.v 
	FILES+=../design_composed/16x16_from_8x8.wrap.v 
	FILES+=../design_organized/8x8.organized.no_conv.no_accum.gen.v  
	DEFINES=+define+MATMUL_SIZE_8 +define+DESIGN_SIZE_16
	TEST_FILES=../verif_organized/layer_test.v 
endif

ifeq ($(size),16_from_combined)
	FILES=../design_composed/16x16_from_8x8.int8.no_ram.gen.for_combined_matmul.v
	FILES+=../design_composed/16x16_from_8x8.wrap.v 
	FILES+=../matmul/8x8int8.4x4fp16.organized.combined.v 
  FILES+=/home/projects/ljohn/aarora1/samidh_internship2020/Internship_2020/floating_point/16_bit/fp16_multiplier_modif.v 
  FILES+=/home/projects/ljohn/aarora1/samidh_internship2020/Internship_2020/floating_point/32_bit/Stratix10/DSP_Slice/FpAddSub_single.modif.v 
  FILES+=/home/projects/ljohn/aarora1/samidh_internship2020/Internship_2020/floating_point/converter_fp/fp16_to_fp32.v 
  FILES+=/home/projects/ljohn/aarora1/samidh_internship2020/Internship_2020/floating_point/converter_fp/fp32_to_fp16.v 
	DEFINES=+define+MATMUL_SIZE_8 +define+DESIGN_SIZE_16
	TEST_FILES=../verif_organized/layer_test.v 
endif

ifeq ($(size),16_from_combined.one_file)
	FILES=../design_composed/tpu_16x16.int8.fpga_with_matmul.v
	FILES+=../matmul/8x8int8.4x4fp16.organized.combined.v 
  FILES+=/home/projects/ljohn/aarora1/samidh_internship2020/Internship_2020/floating_point/16_bit/fp16_multiplier_modif.v 
  FILES+=/home/projects/ljohn/aarora1/samidh_internship2020/Internship_2020/floating_point/32_bit/Stratix10/DSP_Slice/FpAddSub_single.modif.v 
  FILES+=/home/projects/ljohn/aarora1/samidh_internship2020/Internship_2020/floating_point/converter_fp/fp16_to_fp32.v 
  FILES+=/home/projects/ljohn/aarora1/samidh_internship2020/Internship_2020/floating_point/converter_fp/fp32_to_fp16.v 
	DEFINES=+define+MATMUL_SIZE_8 +define+DESIGN_SIZE_16
	TEST_FILES=../verif_organized/layer_test.v 
endif

ifeq ($(size),32)
	FILES=../design_composed/32x32_from_8x8.no_ram.gen.v 
	FILES+=../design_composed/32x32_from_8x8.wrap.v 
	FILES+=../design_organized/8x8.organized.no_conv.no_accum.gen.v  
	DEFINES=+define+MATMUL_SIZE_8 +define+DESIGN_SIZE_32
	TEST_FILES=../verif_organized/layer_test.v 
endif

ifeq ($(size),32_from_combined)
	FILES=../design_composed/32x32_from_8x8.int8.no_ram.gen.for_combined_matmul.v
	FILES+=../design_composed/32x32_from_8x8.wrap.v 
	FILES+=../matmul/8x8int8.4x4fp16.organized.combined.modes.v 
  FILES+=/home/projects/ljohn/aarora1/samidh_internship2020/Internship_2020/floating_point/16_bit/fp16_multiplier_modif.v 
  FILES+=/home/projects/ljohn/aarora1/samidh_internship2020/Internship_2020/floating_point/32_bit/Stratix10/DSP_Slice/FpAddSub_single.modif.v 
  FILES+=/home/projects/ljohn/aarora1/samidh_internship2020/Internship_2020/floating_point/converter_fp/fp16_to_fp32.v 
  FILES+=/home/projects/ljohn/aarora1/samidh_internship2020/Internship_2020/floating_point/converter_fp/fp32_to_fp16.v 
	DEFINES=+define+MATMUL_SIZE_8 +define+DESIGN_SIZE_32
	TEST_FILES=../verif_organized/layer_test.v 
endif

ifeq ($(size),32_from_combined.matmul.one_file)
	FILES=../design_composed/tpu_32x32.int8.fpga_with_matmul.v
	FILES+=../matmul/8x8int8.4x4fp16.organized.combined.modes.v 
  FILES+=/home/projects/ljohn/aarora1/samidh_internship2020/Internship_2020/floating_point/16_bit/fp16_multiplier_modif.v 
  FILES+=/home/projects/ljohn/aarora1/samidh_internship2020/Internship_2020/floating_point/32_bit/Stratix10/DSP_Slice/FpAddSub_single.modif.v 
  FILES+=/home/projects/ljohn/aarora1/samidh_internship2020/Internship_2020/floating_point/converter_fp/fp16_to_fp32.v 
  FILES+=/home/projects/ljohn/aarora1/samidh_internship2020/Internship_2020/floating_point/converter_fp/fp32_to_fp16.v 
	DEFINES=+define+MATMUL_SIZE_8 +define+DESIGN_SIZE_32
	TEST_FILES=../verif_organized/layer_test.v 
endif

ifeq ($(size),32_from_combined.dsp.one_file)
	FILES=../design_composed/tpu_32x32.int8.fpga_with_dsp.v
	DEFINES=+define+MATMUL_SIZE_8 +define+DESIGN_SIZE_32
	TEST_FILES=../verif_organized/layer_test.v 
endif

ifeq ($(size),16.one_file)
	FILES=tpu.16x16.int8.v
	DEFINES=+define+MATMUL_SIZE_8 +define+DESIGN_SIZE_16 +define+SIMULATION
	TEST_FILES=../verif_organized/layer_test.v 
endif

ifeq ($(size),32.one_file)
	FILES=tpu.32x32.int8.v
	DEFINES=+define+MATMUL_SIZE_8 +define+DESIGN_SIZE_32 +define+SIMULATION
	TEST_FILES=../verif_organized/layer_test.v 
endif

compile:
	$(VCS_HOME)/bin/vcs -full64 \
	$(DEFINES) \
	../design_organized/defines.v \
	$(FILES) \
	../design_organized/cfg.v \
	../design_organized/norm.v \
	../design_organized/ram.v \
	../design_organized/control.v \
	../design_organized/pool.v \
	../design_organized/activation.v \
	../design_organized/top.v \
	$(TEST_FILES) \
	../verif_organized/top_tb.v \
	-sverilog \
	-debug_access+all \
	-y /misc/linuxws/packages/synopsys_2018/syn/O-2018.06-SP5/dw/sim_ver \
	-v /misc/linuxws/packages/synopsys_2018/syn/O-2018.06-SP5/dw/sim_ver \
	+define+SIMULATION \
	+libext+.v

help:
	$(VCS_HOME)/bin/vcs -full64 -h 

compile_one_file_design:
	$(VCS_HOME)/bin/vcs -full64  \
	+define+VCS \
  $(DEFINES) \
	$(FILES) \
	$(TEST_FILES) \
	../verif_organized/top_tb.v \
	-sverilog \
  -debug_access+all \
	-y /misc/linuxws/packages/synopsys_2018/syn/O-2018.06-SP5/dw/sim_ver \
	-v /misc/linuxws/packages/synopsys_2018/syn/O-2018.06-SP5/dw/sim_ver \
	+libext+.v

run:
	./simv +layer_test +pool_disabled +activation_disabled +norm_disabled

run_all_enabled:
	./simv +layer_test 

run_norm_disabled:
	./simv +layer_test +norm_disabled

run_pool_disabled:
	./simv +layer_test +pool_disabled

run_activation_disabled:
	./simv +layer_test +activation_disabled

run_accumulator:
	./simv +accum_test +norm_disabled +pool_disabled +activation_disabled

run_npo2:
	./simv +npo2_test +norm_disabled +pool_disabled +activation_disabled

run_conv_no_pad:
	./simv +conv_test_no_padding +norm_disabled +pool_disabled +activation_disabled

run_conv_pad:
	./simv +conv_test_with_padding +norm_disabled +pool_disabled +activation_disabled

waves:
	$(VCS_HOME)/bin/dve -vpd vcdplus.vpd

clean:
	\rm -rf csrc DVEfiles simv.daidir simv ucli.key vcdplus.vpd *.syn *.pvl *.mr *.svf command.log

#Paths when not using LRC machines
#export VCS_HOME /home/tools/vcs/mx-2017.12-SP1-1
#-y /home/tools/synopsys/syn_2017.09/dw/sim_ver \
#-v /home/tools/synopsys/syn_2017.09/dw/sim_ver \

