//----------------------------------------------------------------------------//
// Generated by LegUp High-Level Synthesis Tool Version 4.0 (http://legup.org)
// Compiled: Sun Jul 26 12:56:54 2015
// University of Toronto
// For research and academic purposes only. Commercial use is prohibited.
// Please send bugs to: legup@eecg.toronto.edu
// Date: Tue Aug 11 21:17:20 2020
//----------------------------------------------------------------------------//

`define MEMORY_CONTROLLER_ADDR_SIZE 64
`define MEMORY_CONTROLLER_DATA_SIZE 64
// Number of RAM elements: 5
`define MEMORY_CONTROLLER_TAG_SIZE 9
// @param0 = internal global [1 x [64 x float]] zeroinitializer, align 8
`define TAG_g_param0 `MEMORY_CONTROLLER_TAG_SIZE'd6
`define TAG_g_param0_a {`TAG_g_param0, 55'd0}
// @param1 = internal global [64 x float] zeroinitializer, align 8
`define TAG_g_param1 `MEMORY_CONTROLLER_TAG_SIZE'd5
`define TAG_g_param1_a {`TAG_g_param1, 55'd0}
// @param2 = internal global float 0.000000e+00, align 8
`define TAG_g_param2 `MEMORY_CONTROLLER_TAG_SIZE'd4
`define TAG_g_param2_a {`TAG_g_param2, 55'd0}
// @temp0 = internal unnamed_addr global [1 x [64 x float]] zeroinitializer, align 8
`define TAG_g_temp0 `MEMORY_CONTROLLER_TAG_SIZE'd3
`define TAG_g_temp0_a {`TAG_g_temp0, 55'd0}
// @temp1 = internal global [64 x float] zeroinitializer, align 8
`define TAG_g_temp1 `MEMORY_CONTROLLER_TAG_SIZE'd2
`define TAG_g_temp1_a {`TAG_g_temp1, 55'd0}

// Turn off warning 'ignoring unsupported system task'
// altera message_off 10175

`timescale 1 ns / 1 ns
module top
	(
		clk,
		reset,
		start,
		finish,
		waitrequest,
		return_val
	);
input clk;
input reset;
input start;
output wire finish;
input waitrequest;
output wire [31:0] return_val;
wire memory_controller_waitrequest;
wire memory_controller_enable_a;
wire [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] memory_controller_address_a;
wire memory_controller_write_enable_a;
wire [`MEMORY_CONTROLLER_DATA_SIZE-1:0] memory_controller_in_a;
wire [1:0] memory_controller_size_a;
wire [`MEMORY_CONTROLLER_DATA_SIZE-1:0] memory_controller_out_a;

wire memory_controller_enable_b;
wire [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] memory_controller_address_b;
wire memory_controller_write_enable_b;
wire [`MEMORY_CONTROLLER_DATA_SIZE-1:0] memory_controller_in_b;
wire [1:0] memory_controller_size_b;
wire [`MEMORY_CONTROLLER_DATA_SIZE-1:0] memory_controller_out_b;

/* synthesis translate_off */
assign memory_controller_waitrequest = waitrequest;
/* synthesis translate_on */

memory_controller memory_controller_inst (
	.clk( clk ),
	.memory_controller_enable_a( memory_controller_enable_a ),
	.memory_controller_enable_b( memory_controller_enable_b ),
	.memory_controller_address_a( memory_controller_address_a ),
	.memory_controller_address_b( memory_controller_address_b ),
	.memory_controller_write_enable_a( memory_controller_write_enable_a ),
	.memory_controller_write_enable_b( memory_controller_write_enable_b ),
	.memory_controller_in_a( memory_controller_in_a ),
	.memory_controller_in_b( memory_controller_in_b ),
	.memory_controller_size_a( memory_controller_size_a ),
	.memory_controller_size_b( memory_controller_size_b ),
	.memory_controller_waitrequest( memory_controller_waitrequest ),
	.memory_controller_out_reg_a( memory_controller_out_a ),
	.memory_controller_out_reg_b( memory_controller_out_b )
);

main main_inst(
	.clk( clk ),
	.clk2x( clk2x ),
	.clk1x_follower( clk1x_follower ),
	.reset( reset ),
	.start( start ),
	.finish( finish ),
	.return_val( return_val ),
	.memory_controller_waitrequest(memory_controller_waitrequest),
	.memory_controller_enable_a(memory_controller_enable_a),
	.memory_controller_address_a(memory_controller_address_a),
	.memory_controller_write_enable_a(memory_controller_write_enable_a),
	.memory_controller_in_a(memory_controller_in_a),
	.memory_controller_size_a(memory_controller_size_a),
	.memory_controller_out_a(memory_controller_out_a),
	.memory_controller_enable_b(memory_controller_enable_b),
	.memory_controller_address_b(memory_controller_address_b),
	.memory_controller_write_enable_b(memory_controller_write_enable_b),
	.memory_controller_in_b(memory_controller_in_b),
	.memory_controller_size_b(memory_controller_size_b),
	.memory_controller_out_b(memory_controller_out_b)
);

endmodule

`timescale 1 ns / 1 ns
module memory_controller
(
	clk,
	memory_controller_address_a,
	memory_controller_address_b,
	memory_controller_enable_a,
	memory_controller_enable_b,
	memory_controller_write_enable_a,
	memory_controller_write_enable_b,
	memory_controller_in_a,
	memory_controller_in_b,
	memory_controller_size_a,
	memory_controller_size_b,
	memory_controller_waitrequest,
	memory_controller_out_reg_a,
	memory_controller_out_reg_b
);

parameter latency = 2;

parameter ram_latency = latency-1;

integer j;

input clk;
input memory_controller_waitrequest;
input [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] memory_controller_address_a;
input memory_controller_enable_a;
input memory_controller_write_enable_a;
input [64-1:0] memory_controller_in_a;
input [1:0] memory_controller_size_a;
output reg [64-1:0] memory_controller_out_reg_a;
reg [64-1:0] memory_controller_out_prev_a;
reg [64-1:0] memory_controller_out_a;

reg memory_controller_enable_reg_a;
input [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] memory_controller_address_b;
input memory_controller_enable_b;
input memory_controller_write_enable_b;
input [64-1:0] memory_controller_in_b;
input [1:0] memory_controller_size_b;
output reg [64-1:0] memory_controller_out_reg_b;
reg [64-1:0] memory_controller_out_prev_b;
reg [64-1:0] memory_controller_out_b;

reg memory_controller_enable_reg_b;

reg [5:0] temp1_address_a;
reg [5:0] temp1_address_b;
reg temp1_write_enable_a;
reg temp1_write_enable_b;
reg [31:0] temp1_in_a;
reg [31:0] temp1_in_b;
wire [31:0] temp1_out_a;
wire [31:0] temp1_out_b;

// @temp1 = internal global [64 x float] zeroinitializer, align 8
ram_dual_port temp1 (
	.clk( clk ),
	.clken( !memory_controller_waitrequest ),
	.address_a( temp1_address_a ),
	.address_b( temp1_address_b ),
	.wren_a( temp1_write_enable_a ),
	.wren_b( temp1_write_enable_b ),
	.data_a( temp1_in_a ),
	.data_b( temp1_in_b ),
	.byteena_a( 1'b1 ),
	.byteena_b( 1'b1 ),
	.q_a( temp1_out_a ),
	.q_b( temp1_out_b)
);
defparam temp1.width_a = 32;
defparam temp1.width_b = 32;
defparam temp1.widthad_a = 6;
defparam temp1.widthad_b = 6;
defparam temp1.width_be_a = 1;
defparam temp1.width_be_b = 1;
defparam temp1.numwords_a = 64;
defparam temp1.numwords_b = 64;
defparam temp1.latency = ram_latency;
defparam temp1.init_file = "temp1.mif";

reg [5:0] temp0_address_a;
reg [5:0] temp0_address_b;
reg temp0_write_enable_a;
reg temp0_write_enable_b;
reg [31:0] temp0_in_a;
reg [31:0] temp0_in_b;
wire [31:0] temp0_out_a;
wire [31:0] temp0_out_b;

// @temp0 = internal unnamed_addr global [1 x [64 x float]] zeroinitializer, align 8
ram_dual_port temp0 (
	.clk( clk ),
	.clken( !memory_controller_waitrequest ),
	.address_a( temp0_address_a ),
	.address_b( temp0_address_b ),
	.wren_a( temp0_write_enable_a ),
	.wren_b( temp0_write_enable_b ),
	.data_a( temp0_in_a ),
	.data_b( temp0_in_b ),
	.byteena_a( 1'b1 ),
	.byteena_b( 1'b1 ),
	.q_a( temp0_out_a ),
	.q_b( temp0_out_b)
);
defparam temp0.width_a = 32;
defparam temp0.width_b = 32;
defparam temp0.widthad_a = 6;
defparam temp0.widthad_b = 6;
defparam temp0.width_be_a = 1;
defparam temp0.width_be_b = 1;
defparam temp0.numwords_a = 64;
defparam temp0.numwords_b = 64;
defparam temp0.latency = ram_latency;
defparam temp0.init_file = "temp0.mif";

reg [0:0] param2_address_a;
reg [0:0] param2_address_b;
reg param2_write_enable_a;
reg param2_write_enable_b;
reg [31:0] param2_in_a;
reg [31:0] param2_in_b;
wire [31:0] param2_out_a;
wire [31:0] param2_out_b;

// @param2 = internal global float 0.000000e+00, align 8
ram_dual_port param2 (
	.clk( clk ),
	.clken( !memory_controller_waitrequest ),
	.address_a( param2_address_a ),
	.address_b( param2_address_b ),
	.wren_a( param2_write_enable_a ),
	.wren_b( param2_write_enable_b ),
	.data_a( param2_in_a ),
	.data_b( param2_in_b ),
	.byteena_a( 1'b1 ),
	.byteena_b( 1'b1 ),
	.q_a( param2_out_a ),
	.q_b( param2_out_b)
);
defparam param2.width_a = 32;
defparam param2.width_b = 32;
defparam param2.widthad_a = 1;
defparam param2.widthad_b = 1;
defparam param2.width_be_a = 1;
defparam param2.width_be_b = 1;
defparam param2.numwords_a = 1;
defparam param2.numwords_b = 1;
defparam param2.latency = ram_latency;
defparam param2.init_file = "param2.mif";

reg [5:0] param1_address_a;
reg [5:0] param1_address_b;
reg param1_write_enable_a;
reg param1_write_enable_b;
reg [31:0] param1_in_a;
reg [31:0] param1_in_b;
wire [31:0] param1_out_a;
wire [31:0] param1_out_b;

// @param1 = internal global [64 x float] zeroinitializer, align 8
ram_dual_port param1 (
	.clk( clk ),
	.clken( !memory_controller_waitrequest ),
	.address_a( param1_address_a ),
	.address_b( param1_address_b ),
	.wren_a( param1_write_enable_a ),
	.wren_b( param1_write_enable_b ),
	.data_a( param1_in_a ),
	.data_b( param1_in_b ),
	.byteena_a( 1'b1 ),
	.byteena_b( 1'b1 ),
	.q_a( param1_out_a ),
	.q_b( param1_out_b)
);
defparam param1.width_a = 32;
defparam param1.width_b = 32;
defparam param1.widthad_a = 6;
defparam param1.widthad_b = 6;
defparam param1.width_be_a = 1;
defparam param1.width_be_b = 1;
defparam param1.numwords_a = 64;
defparam param1.numwords_b = 64;
defparam param1.latency = ram_latency;
defparam param1.init_file = "param1.mif";

reg [5:0] param0_address_a;
reg [5:0] param0_address_b;
reg param0_write_enable_a;
reg param0_write_enable_b;
reg [31:0] param0_in_a;
reg [31:0] param0_in_b;
wire [31:0] param0_out_a;
wire [31:0] param0_out_b;

// @param0 = internal global [1 x [64 x float]] zeroinitializer, align 8
ram_dual_port param0 (
	.clk( clk ),
	.clken( !memory_controller_waitrequest ),
	.address_a( param0_address_a ),
	.address_b( param0_address_b ),
	.wren_a( param0_write_enable_a ),
	.wren_b( param0_write_enable_b ),
	.data_a( param0_in_a ),
	.data_b( param0_in_b ),
	.byteena_a( 1'b1 ),
	.byteena_b( 1'b1 ),
	.q_a( param0_out_a ),
	.q_b( param0_out_b)
);
defparam param0.width_a = 32;
defparam param0.width_b = 32;
defparam param0.widthad_a = 6;
defparam param0.widthad_b = 6;
defparam param0.width_be_a = 1;
defparam param0.width_be_b = 1;
defparam param0.numwords_a = 64;
defparam param0.numwords_b = 64;
defparam param0.latency = ram_latency;
defparam param0.init_file = "param0.mif";
wire [`MEMORY_CONTROLLER_TAG_SIZE-1:0] tag_a;
assign tag_a = memory_controller_address_a[`MEMORY_CONTROLLER_ADDR_SIZE-1:`MEMORY_CONTROLLER_ADDR_SIZE-`MEMORY_CONTROLLER_TAG_SIZE];
reg [2:0] prevAddr_a;
reg [1:0] prevSize_a;
reg [2:0] prevSize_a_and;

always @(posedge clk)
if (!memory_controller_waitrequest)
begin
	prevAddr_a <= memory_controller_address_a[2:0];
	prevSize_a <= memory_controller_size_a;
end
wire [`MEMORY_CONTROLLER_TAG_SIZE-1:0] tag_b;
assign tag_b = memory_controller_address_b[`MEMORY_CONTROLLER_ADDR_SIZE-1:`MEMORY_CONTROLLER_ADDR_SIZE-`MEMORY_CONTROLLER_TAG_SIZE];
reg [2:0] prevAddr_b;
reg [1:0] prevSize_b;
reg [2:0] prevSize_b_and;

always @(posedge clk)
if (!memory_controller_waitrequest)
begin
	prevAddr_b <= memory_controller_address_b[2:0];
	prevSize_b <= memory_controller_size_b;
end

reg [2:0] select_not_struct_a;

wire select_temp1_a;
assign select_temp1_a = (tag_a == `TAG_g_temp1);
reg [ram_latency:0] select_temp1_reg_a;
wire [31:0] memory_controller_temp1_out_a;
assign memory_controller_temp1_out_a = {32{ select_temp1_reg_a[ram_latency]}} & temp1_out_a;

wire select_temp0_a;
assign select_temp0_a = (tag_a == `TAG_g_temp0);
reg [ram_latency:0] select_temp0_reg_a;
wire [31:0] memory_controller_temp0_out_a;
assign memory_controller_temp0_out_a = {32{ select_temp0_reg_a[ram_latency]}} & temp0_out_a;

wire select_param2_a;
assign select_param2_a = (tag_a == `TAG_g_param2);
reg [ram_latency:0] select_param2_reg_a;
wire [31:0] memory_controller_param2_out_a;
assign memory_controller_param2_out_a = {32{ select_param2_reg_a[ram_latency]}} & param2_out_a;

wire select_param1_a;
assign select_param1_a = (tag_a == `TAG_g_param1);
reg [ram_latency:0] select_param1_reg_a;
wire [31:0] memory_controller_param1_out_a;
assign memory_controller_param1_out_a = {32{ select_param1_reg_a[ram_latency]}} & param1_out_a;

wire select_param0_a;
assign select_param0_a = (tag_a == `TAG_g_param0);
reg [ram_latency:0] select_param0_reg_a;
wire [31:0] memory_controller_param0_out_a;
assign memory_controller_param0_out_a = {32{ select_param0_reg_a[ram_latency]}} & param0_out_a;

always @(*)
begin
	temp1_address_a = memory_controller_address_a [6-1+2:2] & {6{select_temp1_a}};
	temp1_write_enable_a = memory_controller_write_enable_a & select_temp1_a;
	temp1_in_a [32-1:0] = memory_controller_in_a[32-1:0];

	temp0_address_a = memory_controller_address_a [6-1+2:2] & {6{select_temp0_a}};
	temp0_write_enable_a = memory_controller_write_enable_a & select_temp0_a;
	temp0_in_a [32-1:0] = memory_controller_in_a[32-1:0];

	param2_address_a = memory_controller_address_a [1-1+2:2] & {1{select_param2_a}};
	param2_write_enable_a = memory_controller_write_enable_a & select_param2_a;
	param2_in_a [32-1:0] = memory_controller_in_a[32-1:0];

	param1_address_a = memory_controller_address_a [6-1+2:2] & {6{select_param1_a}};
	param1_write_enable_a = memory_controller_write_enable_a & select_param1_a;
	param1_in_a [32-1:0] = memory_controller_in_a[32-1:0];

	param0_address_a = memory_controller_address_a [6-1+2:2] & {6{select_param0_a}};
	param0_write_enable_a = memory_controller_write_enable_a & select_param0_a;
	param0_in_a [32-1:0] = memory_controller_in_a[32-1:0];

end
always @(*)
begin
	select_not_struct_a [2:0] = 3'b0 | {2{select_temp1_reg_a[ram_latency]}} | {2{select_temp0_reg_a[ram_latency]}} | {2{select_param2_reg_a[ram_latency]}} | {2{select_param1_reg_a[ram_latency]}} | {2{select_param0_reg_a[ram_latency]}};
	if (prevAddr_a[2:0] & select_not_struct_a[2:0] != 0 && memory_controller_enable_a)
	begin
		$display("Error: memory address not aligned to ram word size!");
		$finish;
	end

	prevSize_a_and[0] = prevSize_a[1] | prevSize_a[0];
	prevSize_a_and[1] = prevSize_a[1];
	prevSize_a_and[2] = prevSize_a[1] & prevSize_a[0];
	if ((prevAddr_a & prevSize_a_and) != 0 && memory_controller_enable_a)
	begin
		$display("Error: memory address not aligned to ram word size!");
		$finish;
	end
	memory_controller_out_prev_a = memory_controller_out_reg_a & { 64{!memory_controller_enable_reg_a}};
	memory_controller_out_a = 1'b0 | memory_controller_out_prev_a | memory_controller_temp1_out_a | memory_controller_temp0_out_a | memory_controller_param2_out_a | memory_controller_param1_out_a | memory_controller_param0_out_a;
end

always @(posedge clk)
if (!memory_controller_waitrequest)
begin
memory_controller_out_reg_a <= memory_controller_out_a;
memory_controller_enable_reg_a <= memory_controller_enable_a;
end

always @(posedge clk)
if (!memory_controller_waitrequest)
for (j = 0; j < ram_latency; j=j+1)
begin
select_temp1_reg_a[j+1] <= select_temp1_reg_a[j];
select_temp0_reg_a[j+1] <= select_temp0_reg_a[j];
select_param2_reg_a[j+1] <= select_param2_reg_a[j];
select_param1_reg_a[j+1] <= select_param1_reg_a[j];
select_param0_reg_a[j+1] <= select_param0_reg_a[j];
end
always @(*)
begin
select_temp1_reg_a[0] <= select_temp1_a;
select_temp0_reg_a[0] <= select_temp0_a;
select_param2_reg_a[0] <= select_param2_a;
select_param1_reg_a[0] <= select_param1_a;
select_param0_reg_a[0] <= select_param0_a;
end

reg [2:0] select_not_struct_b;

wire select_temp1_b;
assign select_temp1_b = (tag_b == `TAG_g_temp1);
reg [ram_latency:0] select_temp1_reg_b;
wire [31:0] memory_controller_temp1_out_b;
assign memory_controller_temp1_out_b = {32{ select_temp1_reg_b[ram_latency]}} & temp1_out_b;

wire select_temp0_b;
assign select_temp0_b = (tag_b == `TAG_g_temp0);
reg [ram_latency:0] select_temp0_reg_b;
wire [31:0] memory_controller_temp0_out_b;
assign memory_controller_temp0_out_b = {32{ select_temp0_reg_b[ram_latency]}} & temp0_out_b;

wire select_param2_b;
assign select_param2_b = (tag_b == `TAG_g_param2);
reg [ram_latency:0] select_param2_reg_b;
wire [31:0] memory_controller_param2_out_b;
assign memory_controller_param2_out_b = {32{ select_param2_reg_b[ram_latency]}} & param2_out_b;

wire select_param1_b;
assign select_param1_b = (tag_b == `TAG_g_param1);
reg [ram_latency:0] select_param1_reg_b;
wire [31:0] memory_controller_param1_out_b;
assign memory_controller_param1_out_b = {32{ select_param1_reg_b[ram_latency]}} & param1_out_b;

wire select_param0_b;
assign select_param0_b = (tag_b == `TAG_g_param0);
reg [ram_latency:0] select_param0_reg_b;
wire [31:0] memory_controller_param0_out_b;
assign memory_controller_param0_out_b = {32{ select_param0_reg_b[ram_latency]}} & param0_out_b;

always @(*)
begin
	temp1_address_b = memory_controller_address_b [6-1+2:2] & {6{select_temp1_b}};
	temp1_write_enable_b = memory_controller_write_enable_b & select_temp1_b;
	temp1_in_b [32-1:0] = memory_controller_in_b[32-1:0];

	temp0_address_b = memory_controller_address_b [6-1+2:2] & {6{select_temp0_b}};
	temp0_write_enable_b = memory_controller_write_enable_b & select_temp0_b;
	temp0_in_b [32-1:0] = memory_controller_in_b[32-1:0];

	param2_address_b = memory_controller_address_b [1-1+2:2] & {1{select_param2_b}};
	param2_write_enable_b = memory_controller_write_enable_b & select_param2_b;
	param2_in_b [32-1:0] = memory_controller_in_b[32-1:0];

	param1_address_b = memory_controller_address_b [6-1+2:2] & {6{select_param1_b}};
	param1_write_enable_b = memory_controller_write_enable_b & select_param1_b;
	param1_in_b [32-1:0] = memory_controller_in_b[32-1:0];

	param0_address_b = memory_controller_address_b [6-1+2:2] & {6{select_param0_b}};
	param0_write_enable_b = memory_controller_write_enable_b & select_param0_b;
	param0_in_b [32-1:0] = memory_controller_in_b[32-1:0];

end
always @(*)
begin
	select_not_struct_b [2:0] = 3'b0 | {2{select_temp1_reg_b[ram_latency]}} | {2{select_temp0_reg_b[ram_latency]}} | {2{select_param2_reg_b[ram_latency]}} | {2{select_param1_reg_b[ram_latency]}} | {2{select_param0_reg_b[ram_latency]}};
	if (prevAddr_b[2:0] & select_not_struct_b[2:0] != 0 && memory_controller_enable_b)
	begin
		$display("Error: memory address not aligned to ram word size!");
		$finish;
	end

	prevSize_b_and[0] = prevSize_b[1] | prevSize_b[0];
	prevSize_b_and[1] = prevSize_b[1];
	prevSize_b_and[2] = prevSize_b[1] & prevSize_b[0];
	if ((prevAddr_b & prevSize_b_and) != 0 && memory_controller_enable_b)
	begin
		$display("Error: memory address not aligned to ram word size!");
		$finish;
	end
	memory_controller_out_prev_b = memory_controller_out_reg_b & { 64{!memory_controller_enable_reg_b}};
	memory_controller_out_b = 1'b0 | memory_controller_out_prev_b | memory_controller_temp1_out_b | memory_controller_temp0_out_b | memory_controller_param2_out_b | memory_controller_param1_out_b | memory_controller_param0_out_b;
end

always @(posedge clk)
if (!memory_controller_waitrequest)
begin
memory_controller_out_reg_b <= memory_controller_out_b;
memory_controller_enable_reg_b <= memory_controller_enable_b;
end

always @(posedge clk)
if (!memory_controller_waitrequest)
for (j = 0; j < ram_latency; j=j+1)
begin
select_temp1_reg_b[j+1] <= select_temp1_reg_b[j];
select_temp0_reg_b[j+1] <= select_temp0_reg_b[j];
select_param2_reg_b[j+1] <= select_param2_reg_b[j];
select_param1_reg_b[j+1] <= select_param1_reg_b[j];
select_param0_reg_b[j+1] <= select_param0_reg_b[j];
end
always @(*)
begin
select_temp1_reg_b[0] <= select_temp1_b;
select_temp0_reg_b[0] <= select_temp0_b;
select_param2_reg_b[0] <= select_param2_b;
select_param1_reg_b[0] <= select_param1_b;
select_param0_reg_b[0] <= select_param0_b;
end

endmodule 

`timescale 1 ns / 1 ns
module main
(
	clk,
	clk2x,
	clk1x_follower,
	reset,
	start,
	finish,
	memory_controller_waitrequest,
	memory_controller_enable_a,
	memory_controller_address_a,
	memory_controller_write_enable_a,
	memory_controller_in_a,
	memory_controller_size_a,
	memory_controller_out_a,
	memory_controller_enable_b,
	memory_controller_address_b,
	memory_controller_write_enable_b,
	memory_controller_in_b,
	memory_controller_size_b,
	memory_controller_out_b,
	return_val
);

parameter [5:0] LEGUP_0 = 6'd0;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_1 = 6'd1;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_2 = 6'd2;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_3 = 6'd3;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_4 = 6'd4;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_5 = 6'd5;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_6 = 6'd6;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_7 = 6'd7;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_8 = 6'd8;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_9 = 6'd9;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_10 = 6'd10;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_11 = 6'd11;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_12 = 6'd12;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_13 = 6'd13;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_14 = 6'd14;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_15 = 6'd15;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_16 = 6'd16;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_17 = 6'd17;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_18 = 6'd18;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_19 = 6'd19;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_20 = 6'd20;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_21 = 6'd21;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_22 = 6'd22;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_23 = 6'd23;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_24 = 6'd24;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_25 = 6'd25;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_26 = 6'd26;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_27 = 6'd27;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_28 = 6'd28;
parameter [5:0] LEGUP_F_main_BB_dotloop_exitreduction_29 = 6'd29;
parameter [5:0] LEGUP_F_main_BB_fusionloop_bodydim0preheader_30 = 6'd30;
parameter [5:0] LEGUP_F_main_BB_fusionloop_bodydim0_31 = 6'd31;
parameter [5:0] LEGUP_F_main_BB_fusionloop_bodydim0_32 = 6'd32;
parameter [5:0] LEGUP_F_main_BB_fusionloop_bodydim0_33 = 6'd33;
parameter [5:0] LEGUP_F_main_BB_fusionloop_bodydim0_34 = 6'd34;
parameter [5:0] LEGUP_F_main_BB_fusionloop_bodydim0_35 = 6'd35;
parameter [5:0] LEGUP_F_main_BB_fusionloop_bodydim0_36 = 6'd36;
parameter [5:0] LEGUP_F_main_BB_fusionloop_bodydim0_37 = 6'd37;
parameter [5:0] LEGUP_F_main_BB_fusionloop_bodydim0_38 = 6'd38;
parameter [5:0] LEGUP_F_main_BB_fusionloop_bodydim0_39 = 6'd39;
parameter [5:0] LEGUP_F_main_BB_fusionloop_bodydim0_40 = 6'd40;
parameter [5:0] LEGUP_F_main_BB_fusionloop_bodydim0_41 = 6'd41;
parameter [5:0] LEGUP_F_main_BB_fusionloop_bodydim0_42 = 6'd42;
parameter [5:0] LEGUP_F_main_BB_fusionloop_bodydim0_43 = 6'd43;
parameter [5:0] LEGUP_F_main_BB_fusionloop_bodydim0_44 = 6'd44;
parameter [5:0] LEGUP_F_main_BB_fusionloop_bodydim0_45 = 6'd45;
parameter [5:0] LEGUP_F_main_BB_fusionloop_bodydim0_46 = 6'd46;
parameter [5:0] LEGUP_F_main_BB_fusionloop_bodydim0_47 = 6'd47;
parameter [5:0] LEGUP_F_main_BB_fusionloop_bodydim0_48 = 6'd48;
parameter [5:0] LEGUP_F_main_BB_fusionloop_exitdim0_49 = 6'd49;
parameter [5:0] LEGUP_F_main_BB_fusionloop_exitdim0_50 = 6'd50;
parameter [5:0] LEGUP_F_main_BB_fusionloop_exitdim0_51 = 6'd51;
parameter [8:0] tag_offset = 9'd0;
parameter [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] tag_addr_offset = {tag_offset, 55'd0};

input  clk;
input  clk2x;
input  clk1x_follower;
input  reset;
input  start;
output reg  finish;
input  memory_controller_waitrequest;
output reg  memory_controller_enable_a;
output reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] memory_controller_address_a;
output reg  memory_controller_write_enable_a;
output reg [`MEMORY_CONTROLLER_DATA_SIZE-1:0] memory_controller_in_a;
output reg [1:0] memory_controller_size_a;
input [`MEMORY_CONTROLLER_DATA_SIZE-1:0] memory_controller_out_a;
output reg  memory_controller_enable_b;
output reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] memory_controller_address_b;
output reg  memory_controller_write_enable_b;
output reg [`MEMORY_CONTROLLER_DATA_SIZE-1:0] memory_controller_in_b;
output reg [1:0] memory_controller_size_b;
input [`MEMORY_CONTROLLER_DATA_SIZE-1:0] memory_controller_out_b;
output reg [31:0] return_val;
reg [5:0] cur_state;
reg [5:0] next_state;
reg [63:0] main_dotloop_exitreduction_dotindvarrhs16;
reg [63:0] main_dotloop_exitreduction_dotindvarrhs16_reg;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_dotloop_exitreduction_scevgep5;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_dotloop_exitreduction_scevgep5_reg;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_dotloop_exitreduction_phitransinsert;
reg [31:0] main_dotloop_exitreduction_pre;
reg [31:0] main_dotloop_exitreduction_pre10;
reg [31:0] main_dotloop_exitreduction_0;
reg [31:0] main_dotloop_exitreduction_1;
reg [63:0] main_dotloop_exitreduction_2;
reg [63:0] main_dotloop_exitreduction_2_reg;
reg  main_dotloop_exitreduction_exitcond;
reg  main_dotloop_exitreduction_exitcond_reg;
reg [63:0] main_fusionloop_bodydim0_fusionindvardim02;
reg [63:0] main_fusionloop_bodydim0_fusionindvardim02_reg;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_fusionloop_bodydim0_scevgep;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_fusionloop_bodydim0_scevgep_reg;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_fusionloop_bodydim0_scevgep3;
reg [`MEMORY_CONTROLLER_ADDR_SIZE-1:0] main_fusionloop_bodydim0_scevgep4;
reg [31:0] main_fusionloop_bodydim0_3;
reg [31:0] main_fusionloop_bodydim0_4;
reg [31:0] main_fusionloop_bodydim0_5;
reg [63:0] main_fusionloop_bodydim0_6;
reg [63:0] main_fusionloop_bodydim0_6_reg;
reg  main_fusionloop_bodydim0_exitcond2;
reg  main_fusionloop_bodydim0_exitcond2_reg;
reg [31:0] main_fusionloop_exitdim0_leflow_retval;
reg [31:0] main_altfp_multiply_32_0_op0;
reg [31:0] main_altfp_multiply_32_0_op1;
wire [31:0] altfp_multiplier_main_dotloop_exitreduction_0_out;
reg  altfp_main_dotloop_exitreduction_0_en;
reg [31:0] main_altfp_multiply_32_0;
reg [31:0] main_altfp_add_32_0_op0;
reg [31:0] main_altfp_add_32_0_op1;
wire [31:0] altfp_adder_main_dotloop_exitreduction_1_out;
reg  altfp_main_dotloop_exitreduction_1_en;
reg [31:0] main_altfp_add_32_0;

/*   %0 = fmul float %.pre10, %.pre*/
altfp_multiplier_11 altfp_multiplier_11_main_dotloop_exitreduction_0 (
	.result (altfp_multiplier_main_dotloop_exitreduction_0_out),
	.dataa (main_altfp_multiply_32_0_op0),
	.datab (main_altfp_multiply_32_0_op1),
	.clock (clk),
	.clk_en (altfp_main_dotloop_exitreduction_0_en)
);


/*   %1 = fadd float %0, 0.000000e+00*/
altfp_adder_14 altfp_adder_14_main_dotloop_exitreduction_1 (
	.result (altfp_adder_main_dotloop_exitreduction_1_out),
	.dataa (main_altfp_add_32_0_op0),
	.datab (main_altfp_add_32_0_op1),
	.clock (clk),
	.clk_en (altfp_main_dotloop_exitreduction_1_en)
);



always @(posedge clk) begin
if (reset == 1'b1)
	cur_state <= LEGUP_0;
else if (memory_controller_waitrequest == 1'd1)
	cur_state <= cur_state;
else
	cur_state <= next_state;
end

always @(*)
begin
next_state = cur_state;
case(cur_state)  // synthesis parallel_case  
LEGUP_0:
	if ((start == 1'd1))
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_1;
LEGUP_F_main_BB_dotloop_exitreduction_1:
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_2;
LEGUP_F_main_BB_dotloop_exitreduction_10:
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_11;
LEGUP_F_main_BB_dotloop_exitreduction_11:
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_12;
LEGUP_F_main_BB_dotloop_exitreduction_12:
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_13;
LEGUP_F_main_BB_dotloop_exitreduction_13:
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_14;
LEGUP_F_main_BB_dotloop_exitreduction_14:
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_15;
LEGUP_F_main_BB_dotloop_exitreduction_15:
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_16;
LEGUP_F_main_BB_dotloop_exitreduction_16:
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_17;
LEGUP_F_main_BB_dotloop_exitreduction_17:
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_18;
LEGUP_F_main_BB_dotloop_exitreduction_18:
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_19;
LEGUP_F_main_BB_dotloop_exitreduction_19:
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_20;
LEGUP_F_main_BB_dotloop_exitreduction_2:
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_3;
LEGUP_F_main_BB_dotloop_exitreduction_20:
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_21;
LEGUP_F_main_BB_dotloop_exitreduction_21:
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_22;
LEGUP_F_main_BB_dotloop_exitreduction_22:
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_23;
LEGUP_F_main_BB_dotloop_exitreduction_23:
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_24;
LEGUP_F_main_BB_dotloop_exitreduction_24:
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_25;
LEGUP_F_main_BB_dotloop_exitreduction_25:
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_26;
LEGUP_F_main_BB_dotloop_exitreduction_26:
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_27;
LEGUP_F_main_BB_dotloop_exitreduction_27:
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_28;
LEGUP_F_main_BB_dotloop_exitreduction_28:
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_29;
LEGUP_F_main_BB_dotloop_exitreduction_29:
	if ((main_dotloop_exitreduction_exitcond_reg == 1'd1))
		next_state = LEGUP_F_main_BB_fusionloop_bodydim0preheader_30;
	else if ((main_dotloop_exitreduction_exitcond_reg == 1'd0))
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_1;
LEGUP_F_main_BB_dotloop_exitreduction_3:
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_4;
LEGUP_F_main_BB_dotloop_exitreduction_4:
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_5;
LEGUP_F_main_BB_dotloop_exitreduction_5:
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_6;
LEGUP_F_main_BB_dotloop_exitreduction_6:
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_7;
LEGUP_F_main_BB_dotloop_exitreduction_7:
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_8;
LEGUP_F_main_BB_dotloop_exitreduction_8:
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_9;
LEGUP_F_main_BB_dotloop_exitreduction_9:
		next_state = LEGUP_F_main_BB_dotloop_exitreduction_10;
LEGUP_F_main_BB_fusionloop_bodydim0_31:
		next_state = LEGUP_F_main_BB_fusionloop_bodydim0_32;
LEGUP_F_main_BB_fusionloop_bodydim0_32:
		next_state = LEGUP_F_main_BB_fusionloop_bodydim0_33;
LEGUP_F_main_BB_fusionloop_bodydim0_33:
		next_state = LEGUP_F_main_BB_fusionloop_bodydim0_34;
LEGUP_F_main_BB_fusionloop_bodydim0_34:
		next_state = LEGUP_F_main_BB_fusionloop_bodydim0_35;
LEGUP_F_main_BB_fusionloop_bodydim0_35:
		next_state = LEGUP_F_main_BB_fusionloop_bodydim0_36;
LEGUP_F_main_BB_fusionloop_bodydim0_36:
		next_state = LEGUP_F_main_BB_fusionloop_bodydim0_37;
LEGUP_F_main_BB_fusionloop_bodydim0_37:
		next_state = LEGUP_F_main_BB_fusionloop_bodydim0_38;
LEGUP_F_main_BB_fusionloop_bodydim0_38:
		next_state = LEGUP_F_main_BB_fusionloop_bodydim0_39;
LEGUP_F_main_BB_fusionloop_bodydim0_39:
		next_state = LEGUP_F_main_BB_fusionloop_bodydim0_40;
LEGUP_F_main_BB_fusionloop_bodydim0_40:
		next_state = LEGUP_F_main_BB_fusionloop_bodydim0_41;
LEGUP_F_main_BB_fusionloop_bodydim0_41:
		next_state = LEGUP_F_main_BB_fusionloop_bodydim0_42;
LEGUP_F_main_BB_fusionloop_bodydim0_42:
		next_state = LEGUP_F_main_BB_fusionloop_bodydim0_43;
LEGUP_F_main_BB_fusionloop_bodydim0_43:
		next_state = LEGUP_F_main_BB_fusionloop_bodydim0_44;
LEGUP_F_main_BB_fusionloop_bodydim0_44:
		next_state = LEGUP_F_main_BB_fusionloop_bodydim0_45;
LEGUP_F_main_BB_fusionloop_bodydim0_45:
		next_state = LEGUP_F_main_BB_fusionloop_bodydim0_46;
LEGUP_F_main_BB_fusionloop_bodydim0_46:
		next_state = LEGUP_F_main_BB_fusionloop_bodydim0_47;
LEGUP_F_main_BB_fusionloop_bodydim0_47:
		next_state = LEGUP_F_main_BB_fusionloop_bodydim0_48;
LEGUP_F_main_BB_fusionloop_bodydim0_48:
	if ((main_fusionloop_bodydim0_exitcond2_reg == 1'd1))
		next_state = LEGUP_F_main_BB_fusionloop_exitdim0_49;
	else if ((main_fusionloop_bodydim0_exitcond2_reg == 1'd0))
		next_state = LEGUP_F_main_BB_fusionloop_bodydim0_31;
LEGUP_F_main_BB_fusionloop_bodydim0preheader_30:
		next_state = LEGUP_F_main_BB_fusionloop_bodydim0_31;
LEGUP_F_main_BB_fusionloop_exitdim0_49:
		next_state = LEGUP_F_main_BB_fusionloop_exitdim0_50;
LEGUP_F_main_BB_fusionloop_exitdim0_50:
		next_state = LEGUP_F_main_BB_fusionloop_exitdim0_51;
LEGUP_F_main_BB_fusionloop_exitdim0_51:
		next_state = LEGUP_0;
default:
	next_state = cur_state;
endcase

end
always @(*) begin
	/* main: %dot.loop_exit.reduction*/
	/*   %dot.indvar.rhs.16 = phi i64 [ 0, %dot.loop_body.rhs.1.lr.ph ], [ %2, %dot.loop_exit.reduction ]*/
	if ((((cur_state == LEGUP_0) & (memory_controller_waitrequest == 1'd0)) & (start == 1'd1))) begin
		main_dotloop_exitreduction_dotindvarrhs16 = 64'd0;
	end
	/* main: %dot.loop_exit.reduction*/
	/*   %dot.indvar.rhs.16 = phi i64 [ 0, %dot.loop_body.rhs.1.lr.ph ], [ %2, %dot.loop_exit.reduction ]*/
	else /* if ((((cur_state == LEGUP_F_main_BB_dotloop_exitreduction_29) & (memory_controller_waitrequest == 1'd0)) & (main_dotloop_exitreduction_exitcond_reg == 1'd0))) */ begin
		main_dotloop_exitreduction_dotindvarrhs16 = main_dotloop_exitreduction_2_reg;
	end
end
always @(posedge clk) begin
	/* main: %dot.loop_exit.reduction*/
	/*   %dot.indvar.rhs.16 = phi i64 [ 0, %dot.loop_body.rhs.1.lr.ph ], [ %2, %dot.loop_exit.reduction ]*/
	if ((((cur_state == LEGUP_0) & (memory_controller_waitrequest == 1'd0)) & (start == 1'd1))) begin
		main_dotloop_exitreduction_dotindvarrhs16_reg <= main_dotloop_exitreduction_dotindvarrhs16;
		if (start == 1'b0 && ^(main_dotloop_exitreduction_dotindvarrhs16) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_dotloop_exitreduction_dotindvarrhs16_reg"); $finish; end
	end
	/* main: %dot.loop_exit.reduction*/
	/*   %dot.indvar.rhs.16 = phi i64 [ 0, %dot.loop_body.rhs.1.lr.ph ], [ %2, %dot.loop_exit.reduction ]*/
	if ((((cur_state == LEGUP_F_main_BB_dotloop_exitreduction_29) & (memory_controller_waitrequest == 1'd0)) & (main_dotloop_exitreduction_exitcond_reg == 1'd0))) begin
		main_dotloop_exitreduction_dotindvarrhs16_reg <= main_dotloop_exitreduction_dotindvarrhs16;
		if (start == 1'b0 && ^(main_dotloop_exitreduction_dotindvarrhs16) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_dotloop_exitreduction_dotindvarrhs16_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %dot.loop_exit.reduction*/
	/*   %scevgep5 = getelementptr [1 x [64 x float]]* @temp0, i64 0, i64 0, i64 %dot.indvar.rhs.16*/
		main_dotloop_exitreduction_scevgep5 = (`TAG_g_temp0_a + (64'd4 * main_dotloop_exitreduction_dotindvarrhs16_reg));
end
always @(posedge clk) begin
	/* main: %dot.loop_exit.reduction*/
	/*   %scevgep5 = getelementptr [1 x [64 x float]]* @temp0, i64 0, i64 0, i64 %dot.indvar.rhs.16*/
	if ((cur_state == LEGUP_F_main_BB_dotloop_exitreduction_1)) begin
		main_dotloop_exitreduction_scevgep5_reg <= main_dotloop_exitreduction_scevgep5;
		if (start == 1'b0 && ^(main_dotloop_exitreduction_scevgep5) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_dotloop_exitreduction_scevgep5_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %dot.loop_exit.reduction*/
	/*   %.phi.trans.insert = getelementptr [1 x [64 x float]]* @param0, i64 0, i64 0, i64 %dot.indvar.rhs.16*/
		main_dotloop_exitreduction_phitransinsert = (`TAG_g_param0_a + (64'd4 * main_dotloop_exitreduction_dotindvarrhs16_reg));
end
always @(*) begin
	/* main: %dot.loop_exit.reduction*/
	/*   %.pre = load volatile float* %.phi.trans.insert, align 4*/
		main_dotloop_exitreduction_pre = memory_controller_out_a[31:0];
end
always @(*) begin
	/* main: %dot.loop_exit.reduction*/
	/*   %.pre10 = load volatile float* @param2, align 8*/
		main_dotloop_exitreduction_pre10 = memory_controller_out_b[31:0];
end
always @(*) begin
	main_dotloop_exitreduction_0 = main_altfp_multiply_32_0;
end
always @(*) begin
	main_dotloop_exitreduction_1 = main_altfp_add_32_0;
end
always @(*) begin
	/* main: %dot.loop_exit.reduction*/
	/*   %2 = add nuw nsw i64 %dot.indvar.rhs.16, 1*/
		main_dotloop_exitreduction_2 = (main_dotloop_exitreduction_dotindvarrhs16_reg + 64'd1);
end
always @(posedge clk) begin
	/* main: %dot.loop_exit.reduction*/
	/*   %2 = add nuw nsw i64 %dot.indvar.rhs.16, 1*/
	if ((cur_state == LEGUP_F_main_BB_dotloop_exitreduction_1)) begin
		main_dotloop_exitreduction_2_reg <= main_dotloop_exitreduction_2;
		if (start == 1'b0 && ^(main_dotloop_exitreduction_2) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_dotloop_exitreduction_2_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %dot.loop_exit.reduction*/
	/*   %exitcond = icmp eq i64 %2, 64*/
		main_dotloop_exitreduction_exitcond = (main_dotloop_exitreduction_2 == 64'd64);
end
always @(posedge clk) begin
	/* main: %dot.loop_exit.reduction*/
	/*   %exitcond = icmp eq i64 %2, 64*/
	if ((cur_state == LEGUP_F_main_BB_dotloop_exitreduction_1)) begin
		main_dotloop_exitreduction_exitcond_reg <= main_dotloop_exitreduction_exitcond;
		if (start == 1'b0 && ^(main_dotloop_exitreduction_exitcond) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_dotloop_exitreduction_exitcond_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %fusion.loop_body.dim.0*/
	/*   %fusion.indvar.dim.02 = phi i64 [ %6, %fusion.loop_body.dim.0 ], [ 0, %fusion.loop_body.dim.0.preheader ]*/
	if (((cur_state == LEGUP_F_main_BB_fusionloop_bodydim0preheader_30) & (memory_controller_waitrequest == 1'd0))) begin
		main_fusionloop_bodydim0_fusionindvardim02 = 64'd0;
	end
	/* main: %fusion.loop_body.dim.0*/
	/*   %fusion.indvar.dim.02 = phi i64 [ %6, %fusion.loop_body.dim.0 ], [ 0, %fusion.loop_body.dim.0.preheader ]*/
	else /* if ((((cur_state == LEGUP_F_main_BB_fusionloop_bodydim0_48) & (memory_controller_waitrequest == 1'd0)) & (main_fusionloop_bodydim0_exitcond2_reg == 1'd0))) */ begin
		main_fusionloop_bodydim0_fusionindvardim02 = main_fusionloop_bodydim0_6_reg;
	end
end
always @(posedge clk) begin
	/* main: %fusion.loop_body.dim.0*/
	/*   %fusion.indvar.dim.02 = phi i64 [ %6, %fusion.loop_body.dim.0 ], [ 0, %fusion.loop_body.dim.0.preheader ]*/
	if (((cur_state == LEGUP_F_main_BB_fusionloop_bodydim0preheader_30) & (memory_controller_waitrequest == 1'd0))) begin
		main_fusionloop_bodydim0_fusionindvardim02_reg <= main_fusionloop_bodydim0_fusionindvardim02;
		if (start == 1'b0 && ^(main_fusionloop_bodydim0_fusionindvardim02) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_fusionloop_bodydim0_fusionindvardim02_reg"); $finish; end
	end
	/* main: %fusion.loop_body.dim.0*/
	/*   %fusion.indvar.dim.02 = phi i64 [ %6, %fusion.loop_body.dim.0 ], [ 0, %fusion.loop_body.dim.0.preheader ]*/
	if ((((cur_state == LEGUP_F_main_BB_fusionloop_bodydim0_48) & (memory_controller_waitrequest == 1'd0)) & (main_fusionloop_bodydim0_exitcond2_reg == 1'd0))) begin
		main_fusionloop_bodydim0_fusionindvardim02_reg <= main_fusionloop_bodydim0_fusionindvardim02;
		if (start == 1'b0 && ^(main_fusionloop_bodydim0_fusionindvardim02) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_fusionloop_bodydim0_fusionindvardim02_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %fusion.loop_body.dim.0*/
	/*   %scevgep = getelementptr [64 x float]* @temp1, i64 0, i64 %fusion.indvar.dim.02*/
		main_fusionloop_bodydim0_scevgep = (`TAG_g_temp1_a + (64'd4 * main_fusionloop_bodydim0_fusionindvardim02_reg));
end
always @(posedge clk) begin
	/* main: %fusion.loop_body.dim.0*/
	/*   %scevgep = getelementptr [64 x float]* @temp1, i64 0, i64 %fusion.indvar.dim.02*/
	if ((cur_state == LEGUP_F_main_BB_fusionloop_bodydim0_31)) begin
		main_fusionloop_bodydim0_scevgep_reg <= main_fusionloop_bodydim0_scevgep;
		if (start == 1'b0 && ^(main_fusionloop_bodydim0_scevgep) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_fusionloop_bodydim0_scevgep_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %fusion.loop_body.dim.0*/
	/*   %scevgep3 = getelementptr [1 x [64 x float]]* @temp0, i64 0, i64 0, i64 %fusion.indvar.dim.02*/
		main_fusionloop_bodydim0_scevgep3 = (`TAG_g_temp0_a + (64'd4 * main_fusionloop_bodydim0_fusionindvardim02_reg));
end
always @(*) begin
	/* main: %fusion.loop_body.dim.0*/
	/*   %scevgep4 = getelementptr [64 x float]* @param1, i64 0, i64 %fusion.indvar.dim.02*/
		main_fusionloop_bodydim0_scevgep4 = (`TAG_g_param1_a + (64'd4 * main_fusionloop_bodydim0_fusionindvardim02_reg));
end
always @(*) begin
	/* main: %fusion.loop_body.dim.0*/
	/*   %3 = load volatile float* %scevgep4, align 4*/
		main_fusionloop_bodydim0_3 = memory_controller_out_a[31:0];
end
always @(*) begin
	/* main: %fusion.loop_body.dim.0*/
	/*   %4 = load float* %scevgep3, align 4*/
		main_fusionloop_bodydim0_4 = memory_controller_out_b[31:0];
end
always @(*) begin
	main_fusionloop_bodydim0_5 = main_altfp_add_32_0;
end
always @(*) begin
	/* main: %fusion.loop_body.dim.0*/
	/*   %6 = add nuw nsw i64 %fusion.indvar.dim.02, 1*/
		main_fusionloop_bodydim0_6 = (main_fusionloop_bodydim0_fusionindvardim02_reg + 64'd1);
end
always @(posedge clk) begin
	/* main: %fusion.loop_body.dim.0*/
	/*   %6 = add nuw nsw i64 %fusion.indvar.dim.02, 1*/
	if ((cur_state == LEGUP_F_main_BB_fusionloop_bodydim0_31)) begin
		main_fusionloop_bodydim0_6_reg <= main_fusionloop_bodydim0_6;
		if (start == 1'b0 && ^(main_fusionloop_bodydim0_6) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_fusionloop_bodydim0_6_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %fusion.loop_body.dim.0*/
	/*   %exitcond2 = icmp eq i64 %6, 64*/
		main_fusionloop_bodydim0_exitcond2 = (main_fusionloop_bodydim0_6 == 64'd64);
end
always @(posedge clk) begin
	/* main: %fusion.loop_body.dim.0*/
	/*   %exitcond2 = icmp eq i64 %6, 64*/
	if ((cur_state == LEGUP_F_main_BB_fusionloop_bodydim0_31)) begin
		main_fusionloop_bodydim0_exitcond2_reg <= main_fusionloop_bodydim0_exitcond2;
		if (start == 1'b0 && ^(main_fusionloop_bodydim0_exitcond2) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to main_fusionloop_bodydim0_exitcond2_reg"); $finish; end
	end
end
always @(*) begin
	/* main: %fusion.loop_exit.dim.0*/
	/*   %leflow_retval = load volatile float* getelementptr inbounds ([64 x float]* @temp1, i64 0, i64 0), align 8*/
		main_fusionloop_exitdim0_leflow_retval = memory_controller_out_b[31:0];
end
always @(*) begin
	/* main: %dot.loop_exit.reduction*/
	/*   %0 = fmul float %.pre10, %.pre*/
		main_altfp_multiply_32_0_op0 = main_dotloop_exitreduction_pre10;
end
always @(*) begin
	/* main: %dot.loop_exit.reduction*/
	/*   %0 = fmul float %.pre10, %.pre*/
		main_altfp_multiply_32_0_op1 = main_dotloop_exitreduction_pre;
end
always @(*) begin
	altfp_main_dotloop_exitreduction_0_en = (memory_controller_waitrequest == 1'd0);
end
always @(*) begin
	main_altfp_multiply_32_0 = altfp_multiplier_main_dotloop_exitreduction_0_out;
end
always @(*) begin
	/* main: %dot.loop_exit.reduction*/
	/*   %1 = fadd float %0, 0.000000e+00*/
	if ((cur_state == LEGUP_F_main_BB_dotloop_exitreduction_14)) begin
		main_altfp_add_32_0_op0 = main_dotloop_exitreduction_0;
	end
	/* main: %fusion.loop_body.dim.0*/
	/*   %5 = fadd float %3, %4*/
	else /* if ((cur_state == LEGUP_F_main_BB_fusionloop_bodydim0_33)) */ begin
		main_altfp_add_32_0_op0 = main_fusionloop_bodydim0_3;
	end
end
always @(*) begin
	/* main: %dot.loop_exit.reduction*/
	/*   %1 = fadd float %0, 0.000000e+00*/
	if ((cur_state == LEGUP_F_main_BB_dotloop_exitreduction_14)) begin
		main_altfp_add_32_0_op1 = 32'h0;
	end
	/* main: %fusion.loop_body.dim.0*/
	/*   %5 = fadd float %3, %4*/
	else /* if ((cur_state == LEGUP_F_main_BB_fusionloop_bodydim0_33)) */ begin
		main_altfp_add_32_0_op1 = main_fusionloop_bodydim0_4;
	end
end
always @(*) begin
	altfp_main_dotloop_exitreduction_1_en = (memory_controller_waitrequest == 1'd0);
end
always @(*) begin
	main_altfp_add_32_0 = altfp_adder_main_dotloop_exitreduction_1_out;
end
always @(posedge clk) begin
	if ((cur_state == LEGUP_0)) begin
		finish <= 1'd0;
		if (start == 1'b0 && ^(1'd0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to finish"); $finish; end
	end
	/* main: %fusion.loop_exit.dim.0*/
	/*   ret float %leflow_retval*/
	if ((cur_state == LEGUP_F_main_BB_fusionloop_exitdim0_51)) begin
		finish <= (memory_controller_waitrequest == 1'd0);
		if (start == 1'b0 && ^((memory_controller_waitrequest == 1'd0)) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to finish"); $finish; end
	end
end
always @(*) begin
	memory_controller_enable_a = 1'd0;
	if ((cur_state == LEGUP_0)) begin
		memory_controller_enable_a = 1'd0;
	end
	/* main: %dot.loop_exit.reduction*/
	/*   %.pre = load volatile float* %.phi.trans.insert, align 4*/
	if ((cur_state == LEGUP_F_main_BB_dotloop_exitreduction_1)) begin
		memory_controller_enable_a = 1'd1;
	end
	/* main: %fusion.loop_body.dim.0*/
	/*   %3 = load volatile float* %scevgep4, align 4*/
	if ((cur_state == LEGUP_F_main_BB_fusionloop_bodydim0_31)) begin
		memory_controller_enable_a = 1'd1;
	end
	/* main: %fusion.loop_body.dim.0*/
	/*   store volatile float %5, float* %scevgep, align 4*/
	if ((cur_state == LEGUP_F_main_BB_fusionloop_bodydim0_47)) begin
		memory_controller_enable_a = 1'd1;
	end
end
always @(*) begin
	memory_controller_address_a = 1'd0;
	if ((cur_state == LEGUP_0)) begin
		memory_controller_address_a = 1'd0;
	end
	/* main: %dot.loop_exit.reduction*/
	/*   %.pre = load volatile float* %.phi.trans.insert, align 4*/
	if ((cur_state == LEGUP_F_main_BB_dotloop_exitreduction_1)) begin
		memory_controller_address_a = main_dotloop_exitreduction_phitransinsert;
	end
	/* main: %fusion.loop_body.dim.0*/
	/*   %3 = load volatile float* %scevgep4, align 4*/
	if ((cur_state == LEGUP_F_main_BB_fusionloop_bodydim0_31)) begin
		memory_controller_address_a = main_fusionloop_bodydim0_scevgep4;
	end
	/* main: %fusion.loop_body.dim.0*/
	/*   store volatile float %5, float* %scevgep, align 4*/
	if ((cur_state == LEGUP_F_main_BB_fusionloop_bodydim0_47)) begin
		memory_controller_address_a = main_fusionloop_bodydim0_scevgep_reg;
	end
end
always @(*) begin
	memory_controller_write_enable_a = 1'd0;
	if ((cur_state == LEGUP_0)) begin
		memory_controller_write_enable_a = 1'd0;
	end
	/* main: %dot.loop_exit.reduction*/
	/*   %.pre = load volatile float* %.phi.trans.insert, align 4*/
	if ((cur_state == LEGUP_F_main_BB_dotloop_exitreduction_1)) begin
		memory_controller_write_enable_a = 1'd0;
	end
	/* main: %fusion.loop_body.dim.0*/
	/*   %3 = load volatile float* %scevgep4, align 4*/
	if ((cur_state == LEGUP_F_main_BB_fusionloop_bodydim0_31)) begin
		memory_controller_write_enable_a = 1'd0;
	end
	/* main: %fusion.loop_body.dim.0*/
	/*   store volatile float %5, float* %scevgep, align 4*/
	if ((cur_state == LEGUP_F_main_BB_fusionloop_bodydim0_47)) begin
		memory_controller_write_enable_a = 1'd1;
	end
end
always @(*) begin
	memory_controller_in_a = 1'd0;
	if ((cur_state == LEGUP_0)) begin
		memory_controller_in_a = 1'd0;
	end
	/* main: %fusion.loop_body.dim.0*/
	/*   store volatile float %5, float* %scevgep, align 4*/
	if ((cur_state == LEGUP_F_main_BB_fusionloop_bodydim0_47)) begin
		memory_controller_in_a = main_fusionloop_bodydim0_5;
	end
end
always @(*) begin
	memory_controller_size_a = 1'd0;
	if ((cur_state == LEGUP_0)) begin
		memory_controller_size_a = 1'd0;
	end
	/* main: %dot.loop_exit.reduction*/
	/*   %.pre = load volatile float* %.phi.trans.insert, align 4*/
	if ((cur_state == LEGUP_F_main_BB_dotloop_exitreduction_1)) begin
		memory_controller_size_a = 2'd2;
	end
	/* main: %fusion.loop_body.dim.0*/
	/*   %3 = load volatile float* %scevgep4, align 4*/
	if ((cur_state == LEGUP_F_main_BB_fusionloop_bodydim0_31)) begin
		memory_controller_size_a = 2'd2;
	end
	/* main: %fusion.loop_body.dim.0*/
	/*   store volatile float %5, float* %scevgep, align 4*/
	if ((cur_state == LEGUP_F_main_BB_fusionloop_bodydim0_47)) begin
		memory_controller_size_a = 2'd2;
	end
end
always @(*) begin
	memory_controller_enable_b = 1'd0;
	if ((cur_state == LEGUP_0)) begin
		memory_controller_enable_b = 1'd0;
	end
	/* main: %dot.loop_exit.reduction*/
	/*   %.pre10 = load volatile float* @param2, align 8*/
	if ((cur_state == LEGUP_F_main_BB_dotloop_exitreduction_1)) begin
		memory_controller_enable_b = 1'd1;
	end
	/* main: %dot.loop_exit.reduction*/
	/*   store float %1, float* %scevgep5, align 4*/
	if ((cur_state == LEGUP_F_main_BB_dotloop_exitreduction_28)) begin
		memory_controller_enable_b = 1'd1;
	end
	/* main: %fusion.loop_body.dim.0*/
	/*   %4 = load float* %scevgep3, align 4*/
	if ((cur_state == LEGUP_F_main_BB_fusionloop_bodydim0_31)) begin
		memory_controller_enable_b = 1'd1;
	end
	/* main: %fusion.loop_exit.dim.0*/
	/*   %leflow_retval = load volatile float* getelementptr inbounds ([64 x float]* @temp1, i64 0, i64 0), align 8*/
	if ((cur_state == LEGUP_F_main_BB_fusionloop_exitdim0_49)) begin
		memory_controller_enable_b = 1'd1;
	end
end
always @(*) begin
	memory_controller_address_b = 1'd0;
	if ((cur_state == LEGUP_0)) begin
		memory_controller_address_b = 1'd0;
	end
	/* main: %dot.loop_exit.reduction*/
	/*   %.pre10 = load volatile float* @param2, align 8*/
	if ((cur_state == LEGUP_F_main_BB_dotloop_exitreduction_1)) begin
		memory_controller_address_b = `TAG_g_param2_a;
	end
	/* main: %dot.loop_exit.reduction*/
	/*   store float %1, float* %scevgep5, align 4*/
	if ((cur_state == LEGUP_F_main_BB_dotloop_exitreduction_28)) begin
		memory_controller_address_b = main_dotloop_exitreduction_scevgep5_reg;
	end
	/* main: %fusion.loop_body.dim.0*/
	/*   %4 = load float* %scevgep3, align 4*/
	if ((cur_state == LEGUP_F_main_BB_fusionloop_bodydim0_31)) begin
		memory_controller_address_b = main_fusionloop_bodydim0_scevgep3;
	end
	/* main: %fusion.loop_exit.dim.0*/
	/*   %leflow_retval = load volatile float* getelementptr inbounds ([64 x float]* @temp1, i64 0, i64 0), align 8*/
	if ((cur_state == LEGUP_F_main_BB_fusionloop_exitdim0_49)) begin
		memory_controller_address_b = `TAG_g_temp1_a;
	end
end
always @(*) begin
	memory_controller_write_enable_b = 1'd0;
	if ((cur_state == LEGUP_0)) begin
		memory_controller_write_enable_b = 1'd0;
	end
	/* main: %dot.loop_exit.reduction*/
	/*   %.pre10 = load volatile float* @param2, align 8*/
	if ((cur_state == LEGUP_F_main_BB_dotloop_exitreduction_1)) begin
		memory_controller_write_enable_b = 1'd0;
	end
	/* main: %dot.loop_exit.reduction*/
	/*   store float %1, float* %scevgep5, align 4*/
	if ((cur_state == LEGUP_F_main_BB_dotloop_exitreduction_28)) begin
		memory_controller_write_enable_b = 1'd1;
	end
	/* main: %fusion.loop_body.dim.0*/
	/*   %4 = load float* %scevgep3, align 4*/
	if ((cur_state == LEGUP_F_main_BB_fusionloop_bodydim0_31)) begin
		memory_controller_write_enable_b = 1'd0;
	end
	/* main: %fusion.loop_exit.dim.0*/
	/*   %leflow_retval = load volatile float* getelementptr inbounds ([64 x float]* @temp1, i64 0, i64 0), align 8*/
	if ((cur_state == LEGUP_F_main_BB_fusionloop_exitdim0_49)) begin
		memory_controller_write_enable_b = 1'd0;
	end
end
always @(*) begin
	memory_controller_in_b = 1'd0;
	if ((cur_state == LEGUP_0)) begin
		memory_controller_in_b = 1'd0;
	end
	/* main: %dot.loop_exit.reduction*/
	/*   store float %1, float* %scevgep5, align 4*/
	if ((cur_state == LEGUP_F_main_BB_dotloop_exitreduction_28)) begin
		memory_controller_in_b = main_dotloop_exitreduction_1;
	end
end
always @(*) begin
	memory_controller_size_b = 1'd0;
	if ((cur_state == LEGUP_0)) begin
		memory_controller_size_b = 1'd0;
	end
	/* main: %dot.loop_exit.reduction*/
	/*   %.pre10 = load volatile float* @param2, align 8*/
	if ((cur_state == LEGUP_F_main_BB_dotloop_exitreduction_1)) begin
		memory_controller_size_b = 2'd2;
	end
	/* main: %dot.loop_exit.reduction*/
	/*   store float %1, float* %scevgep5, align 4*/
	if ((cur_state == LEGUP_F_main_BB_dotloop_exitreduction_28)) begin
		memory_controller_size_b = 2'd2;
	end
	/* main: %fusion.loop_body.dim.0*/
	/*   %4 = load float* %scevgep3, align 4*/
	if ((cur_state == LEGUP_F_main_BB_fusionloop_bodydim0_31)) begin
		memory_controller_size_b = 2'd2;
	end
	/* main: %fusion.loop_exit.dim.0*/
	/*   %leflow_retval = load volatile float* getelementptr inbounds ([64 x float]* @temp1, i64 0, i64 0), align 8*/
	if ((cur_state == LEGUP_F_main_BB_fusionloop_exitdim0_49)) begin
		memory_controller_size_b = 2'd2;
	end
end
always @(posedge clk) begin
	if ((cur_state == LEGUP_0)) begin
		return_val <= 0;
		if (start == 1'b0 && ^(0) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to return_val"); $finish; end
	end
	/* main: %fusion.loop_exit.dim.0*/
	/*   ret float %leflow_retval*/
	if ((cur_state == LEGUP_F_main_BB_fusionloop_exitdim0_51)) begin
		return_val <= main_fusionloop_exitdim0_leflow_retval;
		if (start == 1'b0 && ^(main_fusionloop_exitdim0_leflow_retval) === 1'bX) begin $display ("ERROR: Right hand side is 'X'. Assigned to return_val"); $finish; end
	end
end

endmodule 
module ram_dual_port
(
	clk,
	clken,
	address_a,
	address_b,
	wren_a,
	wren_b,
	data_a,
	data_b,
	byteena_a,
	byteena_b,
	q_a,
	q_b
);

parameter  width_a = 1'd0;
parameter  width_b = 1'd0;
parameter  widthad_a = 1'd0;
parameter  widthad_b = 1'd0;
parameter  numwords_a = 1'd0;
parameter  numwords_b = 1'd0;
parameter  init_file = "UNUSED.mif";
parameter  width_be_a = 1'd0;
parameter  width_be_b = 1'd0;
parameter  latency = 1;

input  clk;
input  clken;
input [(widthad_a-1):0] address_a;
input [(widthad_b-1):0] address_b;
output wire [(width_a-1):0] q_a;
output wire [(width_b-1):0] q_b;
reg [(width_a-1):0] q_a_wire;
reg [(width_b-1):0] q_b_wire;
input  wren_a;
input  wren_b;
input [(width_a-1):0] data_a;
input [(width_b-1):0] data_b;
// byte enable is unsupported by inferred RAMs
input [width_be_a-1:0] byteena_a;
input [width_be_b-1:0] byteena_b;

(* ramstyle = "no_rw_check", ram_init_file = init_file *) reg [width_a-1:0] ram[numwords_a-1:0];

/* synthesis translate_off */
integer i;
ALTERA_MF_MEMORY_INITIALIZATION mem ();
reg [8*256:1] ram_ver_file;
initial begin
	if (init_file == "UNUSED.mif")
    begin
		for (i = 0; i < numwords_a; i = i + 1)
			ram[i] = 0;
    end
	else
    begin
        // modelsim can't read .mif files directly. So use Altera function to
        // convert them to .ver files
        mem.convert_to_ver_file(init_file, width_a, ram_ver_file);
        $readmemh(ram_ver_file, ram);
    end
end
/* synthesis translate_on */

always @ (posedge clk)
if (clken)
begin // Port A
if (wren_a)
begin
    ram[address_a] <= data_a;
    q_a_wire <= {width_a{1'bX}};
end
else
    q_a_wire <= ram[address_a];
end
always @ (posedge clk)
if (clken)
begin // Port b
if (wren_b)
begin
    ram[address_b] <= data_b;
    q_b_wire <= {width_b{1'bX}};
end
else
    q_b_wire <= ram[address_b];
end



integer j;
reg [(width_a-1):0] q_a_reg[latency:1], q_b_reg[latency:1];

always @(*)
begin
   q_a_reg[1] <= q_a_wire;
   q_b_reg[1] <= q_b_wire;
end

always @(posedge clk)
if (clken)
begin
   for (j = 1; j < latency; j=j+1)
   begin
       q_a_reg[j+1] <= q_a_reg[j];
       q_b_reg[j+1] <= q_b_reg[j];
   end
end

assign q_a = (clken) ? q_a_reg[latency] : 0;
assign q_b = (clken) ? q_b_reg[latency] : 0;


endmodule
module rom_dual_port
(
	clk,
	clken,
	address_a,
	address_b,
	q_a,
	q_b
);

parameter  width_a = 1'd0;
parameter  width_b = 1'd0;
parameter  widthad_a = 1'd0;
parameter  widthad_b = 1'd0;
parameter  numwords_a = 1'd0;
parameter  numwords_b = 1'd0;
parameter  init_file = "UNUSED.mif";
parameter  latency = 1;

input  clk;
input  clken;
input [(widthad_a-1):0] address_a;
input [(widthad_b-1):0] address_b;
output wire [(width_a-1):0] q_a;
output wire [(width_b-1):0] q_b;
reg [(width_a-1):0] q_a_wire;
reg [(width_b-1):0] q_b_wire;

(* ramstyle = "no_rw_check", ram_init_file = init_file *) reg [width_a-1:0] ram[numwords_a-1:0];

/* synthesis translate_off */
integer i;
ALTERA_MF_MEMORY_INITIALIZATION mem ();
reg [8*256:1] ram_ver_file;
initial begin
	if (init_file == "UNUSED.mif")
    begin
		for (i = 0; i < numwords_a; i = i + 1)
			ram[i] = 0;
    end
	else
    begin
        // modelsim can't read .mif files directly. So use Altera function to
        // convert them to .ver files
        mem.convert_to_ver_file(init_file, width_a, ram_ver_file);
        $readmemh(ram_ver_file, ram);
    end
end
/* synthesis translate_on */

always @ (posedge clk)
if (clken)
begin
    q_a_wire <= ram[address_a];
    q_b_wire <= ram[address_b];
end



integer j;
reg [(width_a-1):0] q_a_reg[latency:1], q_b_reg[latency:1];

always @(*)
begin
   q_a_reg[1] <= q_a_wire;
   q_b_reg[1] <= q_b_wire;
end

always @(posedge clk)
if (clken)
begin
   for (j = 1; j < latency; j=j+1)
   begin
       q_a_reg[j+1] <= q_a_reg[j];
       q_b_reg[j+1] <= q_b_reg[j];
   end
end

assign q_a = (clken) ? q_a_reg[latency] : 0;
assign q_b = (clken) ? q_b_reg[latency] : 0;


endmodule
// Adding code from verilog file: /home/legup/legup-4.0/examples//../boards/Virtex6/ML605/top.v


module ML605 (
       USER_CLOCK,
	    KEY,
	    SW,	    
       LED,
       LEDG,
		UART_RXD,
		UART_TXD

	    );

   input USER_CLOCK;
   input [4:0] KEY;
   input [7:0] SW;
   output [7:0] LED;
   output [7:0] LEDG;
   wire CLOCK_50;

    input UART_RXD;
    output UART_TXD;    
	wire clk = CLOCK_50;
	wire go = ~KEY[1];



   wire 	reset = ~KEY[0];
   wire 	start;
   wire [31:0] 	return_val;
   reg  [31:0] 	return_val_reg;
   wire 	finish;
   wire [3:0]	state;
   
   reg [6:0]   hex0, hex1, hex2, hex3, hex4, hex5, hex6, hex7;

   assign CLOCK_50 = USER_CLOCK;
   assign LED = 0;
   
	always @ (*) begin
		hex7 <= return_val_reg[31:28];
		hex6 <= return_val_reg[27:24];
		hex5 <= return_val_reg[23:20];
		hex4 <= return_val_reg[19:16];
		hex3 <= return_val_reg[15:12];
		hex2 <= return_val_reg[11:8];
		hex1 <= return_val_reg[7:4];
		hex0 <= return_val_reg[3:0];
	end
assign UART_TXD = 1'b0;

    parameter s_WAIT = 3'b001, s_START = 3'b010, s_EXE = 3'b011,
                s_DONE = 3'b100;

    // state registers
    reg [3:0] y_Q, Y_D;

    assign LEDG[3:0] = y_Q;

    // next state
    always @(*)
    begin
        case (y_Q)
            s_WAIT: if (go) Y_D = s_START; else Y_D = y_Q;

            s_START: Y_D = s_EXE;

            s_EXE: if (!finish) Y_D = s_EXE; else Y_D = s_DONE;

            s_DONE: Y_D = s_DONE;

            default: Y_D = 3'bxxx;
        endcase
    end

    // current state
    always @(posedge clk)
    begin
        if (reset) // synchronous clear
            y_Q <= s_WAIT;
        else
            y_Q <= Y_D;
    end

    always @(posedge clk)
        if (y_Q == s_EXE && finish)
            return_val_reg <= return_val;
        else if (y_Q == s_DONE)
            return_val_reg <= return_val_reg;
        else
            return_val_reg <= 0;


    assign start = (y_Q == s_START);

   
   top top_inst (
      .clk (clk),
      .reset (reset),
      .finish (finish),
      .return_val (return_val),
        .start (start)

    );

   

endmodule

// Adding code from verilog file: /home/legup/legup-4.0/examples//../boards/StratixIV/DE4/top.v


module de4 ( 
    	     OSC_50_BANK2, 
             BUTTON, 
             LED, 
    	     SEG0_D, 
    	     SEG1_D 
	     ); 
   input OSC_50_BANK2; 
   input [1:0] BUTTON; 
   output [6:0] SEG0_D; 
   output [6:0] SEG1_D; 
   output [7:0] LED; 
   
   de2 de2_inst ( 
		  .CLOCK_50 (OSC_50_BANK2), 
		  .LEDG (LED), 
		  .KEY (BUTTON), 
		  .SW (), 
		  .HEX0 (SEG0_D), 
		  .HEX1 (SEG1_D), 
		  .HEX2 (), 
		  .HEX3 (), 
		  .HEX4 (), 
		  .HEX5 (), 
		  .HEX6 (), 
		  .HEX7 () 
		  ); 
   
endmodule
// Adding code from verilog file: /home/legup/legup-4.0/examples//../boards/CycloneII/DE2/top.v


module de2 (
	    CLOCK_50,
	    KEY,
	    SW,
	    HEX0,
	    HEX1,
	    HEX2,
	    HEX3,
	    HEX4,
	    HEX5,
	    HEX6,
	    HEX7,
	    LEDG,
		UART_RXD,
		UART_TXD

	    );

   input CLOCK_50;
   input [3:0] KEY;
   input [17:0] SW;
   output [6:0] HEX0, HEX1,  HEX2,  HEX3,  HEX4,  HEX5,  HEX6,  HEX7;
   reg [6:0] 	hex0, hex1, hex2, hex3, hex4, hex5, hex6, hex7;
   

   output [7:0] LEDG;
    input UART_RXD;
    output UART_TXD;    
	wire clk = CLOCK_50;
	wire go = ~KEY[1];



   wire 	reset = ~KEY[0];
   wire 	start;
   wire [31:0] 	return_val;
   reg  [31:0] 	return_val_reg;
   wire 	finish;
   wire [3:0]	state;

   hex_digits h7( .x(hex7), .hex_LEDs(HEX7));
   hex_digits h6( .x(hex6), .hex_LEDs(HEX6));
   hex_digits h5( .x(hex5), .hex_LEDs(HEX5));
   hex_digits h4( .x(hex4), .hex_LEDs(HEX4));
   hex_digits h3( .x(hex3), .hex_LEDs(HEX3));
   hex_digits h2( .x(hex2), .hex_LEDs(HEX2));
   hex_digits h1( .x(hex1), .hex_LEDs(HEX1));
   hex_digits h0( .x(hex0), .hex_LEDs(HEX0));
   
	always @ (*) begin
		hex7 <= return_val_reg[31:28];
		hex6 <= return_val_reg[27:24];
		hex5 <= return_val_reg[23:20];
		hex4 <= return_val_reg[19:16];
		hex3 <= return_val_reg[15:12];
		hex2 <= return_val_reg[11:8];
		hex1 <= return_val_reg[7:4];
		hex0 <= return_val_reg[3:0];
	end
assign UART_TXD = 1'b0;

    parameter s_WAIT = 3'b001, s_START = 3'b010, s_EXE = 3'b011,
                s_DONE = 3'b100;

    // state registers
    reg [3:0] y_Q, Y_D;

    assign LEDG[3:0] = y_Q;

    // next state
    always @(*)
    begin
        case (y_Q)
            s_WAIT: if (go) Y_D = s_START; else Y_D = y_Q;

            s_START: Y_D = s_EXE;

            s_EXE: if (!finish) Y_D = s_EXE; else Y_D = s_DONE;

            s_DONE: Y_D = s_DONE;

            default: Y_D = 3'bxxx;
        endcase
    end

    // current state
    always @(posedge clk)
    begin
        if (reset) // synchronous clear
            y_Q <= s_WAIT;
        else
            y_Q <= Y_D;
    end

    always @(posedge clk)
        if (y_Q == s_EXE && finish)
            return_val_reg <= return_val;
        else if (y_Q == s_DONE)
            return_val_reg <= return_val_reg;
        else
            return_val_reg <= 0;


    assign start = (y_Q == s_START);

   
   top top_inst (
      .clk (clk),
      .reset (reset),
      .finish (finish),
      .return_val (return_val),
        .start (start)

    );

endmodule

module circuit_start_control (
    go,
    control_key
);
    input control_key;
    output go;
    assign go = control_key;
endmodule
module hex_digits(x, hex_LEDs);
    input [3:0] x;
    output [6:0] hex_LEDs;
    
    assign hex_LEDs[0] = (~x[3] & ~x[2] & ~x[1] & x[0]) |
                            (~x[3] & x[2] & ~x[1] & ~x[0]) |
                            (x[3] & x[2] & ~x[1] & x[0]) |
                            (x[3] & ~x[2] & x[1] & x[0]);
    assign hex_LEDs[1] = (~x[3] & x[2] & ~x[1] & x[0]) |
                            (x[3] & x[1] & x[0]) |
                            (x[3] & x[2] & ~x[0]) |
                            (x[2] & x[1] & ~x[0]);
    assign hex_LEDs[2] = (x[3] & x[2] & ~x[0]) |
                            (x[3] & x[2] & x[1]) |
                            (~x[3] & ~x[2] & x[1] & ~x[0]);
    assign hex_LEDs[3] = (~x[3] & ~x[2] & ~x[1] & x[0]) | 
                            (~x[3] & x[2] & ~x[1] & ~x[0]) | 
                            (x[2] & x[1] & x[0]) | 
                            (x[3] & ~x[2] & x[1] & ~x[0]);
    assign hex_LEDs[4] = (~x[3] & x[0]) |
                            (~x[3] & x[2] & ~x[1]) |
                            (~x[2] & ~x[1] & x[0]);
    assign hex_LEDs[5] = (~x[3] & ~x[2] & x[0]) | 
                            (~x[3] & ~x[2] & x[1]) | 
                            (~x[3] & x[1] & x[0]) | 
                            (x[3] & x[2] & ~x[1] & x[0]);
    assign hex_LEDs[6] = (~x[3] & ~x[2] & ~x[1]) | 
                            (x[3] & x[2] & ~x[1] & ~x[0]) | 
                            (~x[3] & x[2] & x[1] & x[0]);
    
endmodule
`timescale 1 ns / 1 ns
module main_tb
(
);

reg  clk;
reg  reset;
reg  start;
reg  waitrequest;
wire [31:0] return_val;
wire  finish;


top top_inst (
	.clk (clk),
	.reset (reset),
	.start (start),
	.waitrequest (waitrequest),
	.finish (finish),
	.return_val (return_val)
);




initial 
    clk = 0;
always @(clk)
    clk <= #10 ~clk;

initial begin
//$monitor("At t=%t clk=%b %b %b %b %d", $time, clk, reset, start, finish, return_val);
@(negedge clk);
reset <= 1;
@(negedge clk);
reset <= 0;
start <= 1;
@(negedge clk);
start <= 0;
end

always@(finish) begin
    if (finish == 1) begin
        $writememh("memory_dump.txt",top_inst.memory_controller_inst.temp1.ram);
        $display("At t=%t clk=%b finish=%b return_val=%d", $time, clk, finish, return_val);
        $display("Cycles: %d", ($time-50)/20);
        $finish;
    end
end

initial begin
waitrequest <= 1;
@(negedge clk);
@(negedge clk);
waitrequest <= 0;
end


endmodule 
